import type { ModelRegistryEntry } from '@group-goki/shared'

export const DEFAULT_MODELS: readonly ModelRegistryEntry[] = [
  // Frontier tier
  {
    id: 'anthropic/claude-opus-4-5',
    name: 'Claude Opus 4.5',
    provider: 'anthropic',
    contextWindow: 200000,
    maxOutputTokens: 32000,
    costPerInputToken: 0.000015,
    costPerOutputToken: 0.000075,
    capabilities: ['strategy', 'technical-architecture', 'research', 'synthesis', 'planning', 'creative-writing'],
    tier: 'frontier',
    active: true,
  },
  {
    id: 'openai/gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    costPerInputToken: 0.0000025,
    costPerOutputToken: 0.00001,
    capabilities: ['code-generation', 'data-analysis', 'creative-writing', 'research', 'debate'],
    tier: 'frontier',
    active: true,
  },
  {
    id: 'google/gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'google',
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    costPerInputToken: 0.00000125,
    costPerOutputToken: 0.00001,
    capabilities: ['research', 'code-generation', 'data-analysis', 'math-reasoning', 'synthesis'],
    tier: 'frontier',
    active: true,
  },

  // Strong tier
  {
    id: 'anthropic/claude-sonnet-4',
    name: 'Claude Sonnet 4',
    provider: 'anthropic',
    contextWindow: 200000,
    maxOutputTokens: 16000,
    costPerInputToken: 0.000003,
    costPerOutputToken: 0.000015,
    capabilities: ['code-generation', 'code-review', 'technical-architecture', 'planning'],
    tier: 'strong',
    active: true,
  },
  {
    id: 'deepseek/deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'deepseek',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    costPerInputToken: 0.00000055,
    costPerOutputToken: 0.0000022,
    capabilities: ['math-reasoning', 'code-generation', 'research', 'planning'],
    tier: 'strong',
    active: true,
  },
  {
    id: 'mistralai/mistral-large-latest',
    name: 'Mistral Large',
    provider: 'mistral',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    costPerInputToken: 0.000002,
    costPerOutputToken: 0.000006,
    capabilities: ['code-generation', 'research', 'debate', 'creative-writing'],
    tier: 'strong',
    active: true,
  },
  {
    id: 'qwen/qwen-2.5-72b-instruct',
    name: 'Qwen 2.5 72B',
    provider: 'qwen',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    costPerInputToken: 0.0000004,
    costPerOutputToken: 0.000002,
    capabilities: ['code-generation', 'math-reasoning', 'research', 'data-analysis'],
    tier: 'strong',
    active: true,
  },

  // Efficient tier
  {
    id: 'anthropic/claude-haiku-3.5',
    name: 'Claude Haiku 3.5',
    provider: 'anthropic',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    costPerInputToken: 0.0000008,
    costPerOutputToken: 0.000004,
    capabilities: ['code-generation', 'code-review', 'planning'],
    tier: 'efficient',
    active: true,
  },
  {
    id: 'openai/gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'openai',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    costPerInputToken: 0.00000015,
    costPerOutputToken: 0.0000006,
    capabilities: ['code-generation', 'data-analysis', 'creative-writing'],
    tier: 'efficient',
    active: true,
  },
  {
    id: 'google/gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'google',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    costPerInputToken: 0.0000001,
    costPerOutputToken: 0.0000004,
    capabilities: ['research', 'data-analysis', 'code-generation'],
    tier: 'efficient',
    active: true,
  },

  // Budget tier
  {
    id: 'meta-llama/llama-3.3-70b-instruct',
    name: 'Llama 3.3 70B',
    provider: 'meta',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    costPerInputToken: 0.0000004,
    costPerOutputToken: 0.0000004,
    capabilities: ['code-generation', 'research', 'debate'],
    tier: 'budget',
    active: true,
  },
  {
    id: 'deepseek/deepseek-chat',
    name: 'DeepSeek V3',
    provider: 'deepseek',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    costPerInputToken: 0.00000014,
    costPerOutputToken: 0.00000028,
    capabilities: ['code-generation', 'math-reasoning', 'data-analysis'],
    tier: 'budget',
    active: true,
  },
]
